version: '3.8'
services:
    db:
        image: postgres
        container_name: vsharee-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: vsharee
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data

    backend:
        container_name: vsharee-backend
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '8000:5000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        depends_on:
            - db

volumes:
    db_data:
