name: Deploy Backend (production)

on:
    push:
        branches: [production]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout (optional)
              uses: actions/checkout@v4

            - name: Prepare SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

            - name: Deploy on server
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  APP_DIR: ${{ secrets.APP_DIR }} # e.g. /opt/vsharee
              run: |
                  # Pass env vars into the remote shell BEFORE the heredoc, keep heredoc quoted
                  ssh -o BatchMode=yes -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 \
                    "${SSH_USER}@${SSH_HOST}" \
                    "APP_DIR='${APP_DIR}' bash -se" << 'EOF'
                  set -euo pipefail

                  cd "${APP_DIR}/vsharee_backend"
                  git fetch --all
                  git checkout production || git checkout -b production
                  git reset --hard origin/production

                  cd "${APP_DIR}"
                  docker compose build backend
                  docker compose up -d --no-deps backend

                  # reload caddy just in case (won't hurt)
                  docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile || true
                  EOF
