name: Deploy Backend (production)

on:
    push:
        branches: [production]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout (not strictly needed, but ok)
              uses: actions/checkout@v4

            - name: Prepare SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

            - name: Deploy on server
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  APP_DIR: ${{ secrets.APP_DIR }}
              run: |
                  ssh -i ~/.ssh/id_ed25519 ${SSH_USER}@${SSH_HOST} << 'EOF'
                  set -euo pipefail
                  cd ${APP_DIR}/vsharee_backend
                  git fetch --all
                  git checkout production || git checkout -b production
                  git reset --hard origin/production

                  cd ${APP_DIR}
                  docker compose build backend
                  docker compose up -d --no-deps backend

                  # If you prefer to apply migrations explicitly:
                  docker compose exec -T backend npx prisma migrate deploy || true
                  EOF
